/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model;


import java.util.Arrays;
import java.util.List;

import org.acumen.training.codes.model.tables.Boat;
import org.acumen.training.codes.model.tables.Reservation;
import org.acumen.training.codes.model.tables.Sailor;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.boat</code>.
     */
    public final Boat BOAT = Boat.BOAT;

    /**
     * The table <code>public.reservation</code>.
     */
    public final Reservation RESERVATION = Reservation.RESERVATION;

    /**
     * The table <code>public.sailor</code>.
     */
    public final Sailor SAILOR = Sailor.SAILOR;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Boat.BOAT,
            Reservation.RESERVATION,
            Sailor.SAILOR
        );
    }
}
