/*
 * This file is generated by jOOQ.
 */
package org.acumen.training.codes.model;


import org.acumen.training.codes.model.tables.Boat;
import org.acumen.training.codes.model.tables.Reservation;
import org.acumen.training.codes.model.tables.Sailor;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.boat</code>.
     */
    public static final Boat BOAT = Boat.BOAT;

    /**
     * The table <code>public.reservation</code>.
     */
    public static final Reservation RESERVATION = Reservation.RESERVATION;

    /**
     * The table <code>public.sailor</code>.
     */
    public static final Sailor SAILOR = Sailor.SAILOR;
}
